---
# These tasks apply to all nodes.

# DNS related tasks
- name: Try to ping ipa-ca
  command: ping -c 3 ipa-ca
  register: ipa_ca_ping_status
  ignore_errors: true
  changed_when: false

- name: Set facts for ok DNS configuration
  set_fact:
    dns_status: '{{ helper_status_ok }}'
    dns_reason: DNS is configured correctly
    dns_recommendations: null
  when: ipa_ca_ping_status.rc == 0

- name: Set facts for error in DNS configuration
  set_fact:
    dns_status: '{{ helper_status_error }}'
    dns_reason: DNS is NOT configured correctly
    dns_recommendations:
      - Check that the DNS server for this node points to IdM/FreeIPA
      - For the undercloud, you need to set the 'undercloud_nameservers' configuration parameter
      - For the overcloud, you need to set the 'DnsServers' parameter
      - Make sure that the relevant 'search' entry is in /etc/resolv.conf
  when: ipa_ca_ping_status.rc != 0

- name: Report DNS status
  import_tasks: reportentry.yml
  vars:
    report_check: "DNS check"
    report_status: '{{ dns_status }}'
    report_host: '{{ ansible_hostname }}'
    report_reason: '{{ dns_reason }}'
    report_recommendations: '{{ dns_recommendations }}'

# Firewall related tasks
- name: Firewall validations
  when: ipa_ca_ping_status.rc == 0
  block:
    - name: Check all relevant ports for IdM/FreeIPA are accessible from {{ ansible_hostname }}
      wait_for:
        host: ipa-ca
        port: "{{ item }}"
        state: started         # Port should be open
        delay: 0               # No wait before first check (sec)
        timeout: 3             # Stop checking after timeout (sec)
      register: port_status
      ignore_errors: true
      loop:
        - 80
        - 443
        - 389
        - 636
        - 88
        - 464
        - 53

    - name: Set facts for ok firewall settings
      set_fact:
        firewall_status: '{{ helper_status_ok }}'
        firewall_reason: "The host {{ ansible_hostname }} can access FreeIPA through all relevant ports"
        firewall_recommendations: null
      when: "'failed' not in port_status"

    - name: Set facts for issues in firewall settings
      set_fact:
        firewall_status: '{{ helper_status_error }}'
        firewall_reason: "The host {{ ansible_hostname }} could NOT access IdM/FreeIPA on some ports"
        firewall_recommendations:
          - "Please make sure that the following ports are open on the IdM/FreeIPA node: {{ firewall_query }}"
      vars:
        firewall_query: "{{ port_status.results | json_query('[?failed].item') | join(', ') }}"
      when:
        - "'failed' in port_status"
        - port_status.failed|bool

- name: Set facts for skipping firewall checks
  set_fact:
    firewall_status: '{{ helper_status_skipped }}'
    firewall_reason: "skipped {{ ansible_hostname }} firewall checks because DNS wasn't set correctly."
    firewall_recommendations: null
  when: ipa_ca_ping_status.rc != 0

- name: Report firewall status
  import_tasks: reportentry.yml
  vars:
    report_check: "Firewall check"
    report_status: '{{ firewall_status }}'
    report_host: '{{ ansible_hostname }}'
    report_reason: '{{ firewall_reason }}'
    report_recommendations: '{{ firewall_recommendations }}'

# IdM/FreeIPA related tasks
- name: Check for IdM/FreeIPA host configuration
  stat:
    path: /etc/ipa/default.conf
  register: ipa_conf_stat

- name: Set facts for IdM/FreeIPA configuration present
  set_fact:
    ipa_conf_status: '{{ helper_status_ok }}'
    ipa_conf_reason: "The host {{ ansible_host }} has the file /etc/ipa/default.conf"
    ipa_conf_recommendations: null
  when: ipa_conf_stat.stat.exists

- name: Set facts for IdM/FreeIPA configuration missing
  set_fact:
    ipa_conf_status: '{{ helper_status_error }}'
    ipa_conf_reason: "The host {{ ansible_host }} is missing the file /etc/ipa/default.conf"
    ipa_conf_recommendations:
      - "The host {{ ansible_host }} needs to be enrolled to IdM/FreeIPA"
      - If there were enrollment issues, you'll see them in /var/log/ipaclient-install.log
  when: not ipa_conf_stat.stat.exists

- name: Report IdM/FreeIPA host configuration status
  import_tasks: reportentry.yml
  vars:
    report_check: "IdM/FreeIPA host configuration check"
    report_status: '{{ ipa_conf_status }}'
    report_host: '{{ ansible_hostname }}'
    report_reason: '{{ ipa_conf_reason }}'
    report_recommendations: '{{ ipa_conf_recommendations }}'
