---
# These tasks apply to all nodes.
- name: Try to ping ipa-ca
  command: ping -c 3 ipa-ca
  register: ipa_ca_ping_status
  ignore_errors: true
  changed_when: false

- name: Set facts for ok DNS configuration
  set_fact:
    dns_status: '{{ helper_status_ok }}'
    dns_reason: DNS is configured correctly
    dns_recommendations: null
  when: ipa_ca_ping_status.rc == 0

- name: Set facts for error in DNS configuration
  set_fact:
    dns_status: '{{ helper_status_error }}'
    dns_reason: DNS is NOT configured correctly
    dns_recommendations:
      - Check that the DNS server for this node points to IdM/FreeIPA
      - For the undercloud, you need to set the 'undercloud_nameservers' configuration parameter
      - For the overcloud, you need to set the 'DnsServers' parameter
      - Make sure that the relevant 'search' entry is in /etc/resolv.conf
  when: ipa_ca_ping_status.rc != 0

- name: Report DNS status
  import_tasks: reportentry.yml
  vars:
    report_status: '{{ dns_status }}'
    report_host: '{{ ansible_hostname }}'
    report_reason: '{{ dns_reason }}'
    report_recommendations: '{{ dns_recommendations }}'
