---
- name: Try to ping ipa-ca
  command: ping -c 3 ipa-ca
  register: ipa_ca_ping_status
  ignore_errors: true
  changed_when: false
  tags:
    - common

- name: Set facts for ok DNS configuration
  set_fact:
    dns_status: '{{ helper_status_ok }}'
    dns_reason: DNS is configured correctly
  when: ipa_ca_ping_status.rc == 0
  tags:
    - common

- name: Set facts for error in DNS configuration
  set_fact:
    dns_status: '{{ helper_status_error }}'
    dns_reason: DNS is NOT configured correctly
  when: ipa_ca_ping_status.rc != 0
  tags:
    - common

- name: Report DNS status
  blockinfile:
    create: true
    marker: ''
    path: /tmp/report.txt
    content: "{{ lookup('template', 'templates/report-template-txt.j2') }}"
  vars:
    report_status: '{{ dns_status }}'
    report_host: '{{ ansible_hostname }}'
    report_reason: '{{ dns_reason }}'
  delegate_to: localhost
  tags:
    - common
