---
- name: Verify that undercloud.conf exists
  stat:
    path: "{{ helper_undercloud_path }}/undercloud.conf"
  register: undercloud_conf_st

# We really can't continue without undercloud.conf
- name: Fail if undercloud.conf is not present
  fail:
    msg: undercloud.conf is necessary to continue the validations
  when: not undercloud_conf_st.stat.exists|bool

# undercloud.conf DNS check
- name: Verify that nameservers are set in undercloud.conf
  set_fact:
    undercloud_nameservers: "{{ lookup('ini', 'undercloud_nameservers section=DEFAULT file={{ helper_undercloud_path }}/undercloud.conf') }}"

- name: Check that nameservers point to IdM/FreeIPA
  set_fact:
    undercloud_conf_dns_query: "{{ lookup('dig', 'ipa-ca', '@{{ item }}') }}"
  loop: "{{ undercloud_nameservers.split(',') }}"
  when: undercloud_nameservers != "" and undercloud_nameservers != []

- name: Set facts undercloud.conf DNS is not configured
  set_fact:
    undercloud_conf_dns_status: '{{ helper_status_error }}'
    undercloud_conf_dns_reason: 'DNS is not set up correctly in undercloud.conf'
    undercloud_conf_dns_recommendations:
      -  "Please set the 'undercloud_nameservers' parameter to point to IdM/FreeIPA in undercloud.conf"
  when: undercloud_conf_dns_query|default('NXDOMAIN') == "NXDOMAIN"

- name: Set facts undercloud.conf DNS is configured
  set_fact:
    undercloud_conf_dns_status: '{{ helper_status_ok }}'
    undercloud_conf_dns_reason: 'DNS is set up correctly in undercloud.conf'
    undercloud_conf_dns_recommendations: null
  when: undercloud_conf_dns_query|default('NXDOMAIN') != "NXDOMAIN"

- name: Report DNS setup in undercloud.conf
  import_tasks: reportentry.yml
  vars:
    report_check: "DNS setup in undercloud.conf check"
    report_status: '{{ undercloud_conf_dns_status }}'
    report_host: '{{ ansible_hostname }}'
    report_reason: '{{ undercloud_conf_dns_reason }}'
    report_recommendations: '{{ undercloud_conf_dns_recommendations }}'
