---
- name: get package facts
  package_facts:
    manager: "auto"

- name: Is the undercloud containerized?
  set_fact:
    containerized_undercloud: "{{ ansible_facts.packages['puppet-keystone'][0].version is version('13', '>=') }}"

- name: Verify that undercloud.conf exists
  stat:
    path: "{{ helper_undercloud_path }}/undercloud.conf"
  register: undercloud_conf_st
  tags:
    - pre-undercloud-deploy

# We really can't continue without undercloud.conf
- name: Fail if undercloud.conf is not present
  fail:
    msg: undercloud.conf is necessary to continue the validations
  when: not undercloud_conf_st.stat.exists|bool
  tags:
    - pre-undercloud-deploy

# undercloud.conf DNS check
- name: Verify that nameservers are set in undercloud.conf
  set_fact:
    undercloud_nameservers: "{{ lookup('ini', 'undercloud_nameservers section=DEFAULT file={{ helper_undercloud_path }}/undercloud.conf') }}"
  tags:
    - pre-undercloud-deploy

- name: Check that nameservers point to IdM/FreeIPA
  set_fact:
    undercloud_conf_dns_query: "{{ lookup('dig', 'ipa-ca', '@{{ item }}') }}"
  loop: "{{ undercloud_nameservers.split(',') }}"
  when: undercloud_nameservers != "" and undercloud_nameservers != []
  tags:
    - pre-undercloud-deploy

- name: Set facts undercloud.conf DNS is not configured
  set_fact:
    undercloud_conf_dns_status: '{{ helper_status_error }}'
    undercloud_conf_dns_reason: 'DNS is not set up correctly in undercloud.conf'
    undercloud_conf_dns_recommendations:
      - "Please set the 'undercloud_nameservers' parameter to point to IdM/FreeIPA in undercloud.conf"
  when: undercloud_conf_dns_query|default('NXDOMAIN') == "NXDOMAIN"
  tags:
    - pre-undercloud-deploy

- name: Set facts undercloud.conf DNS is configured
  set_fact:
    undercloud_conf_dns_status: '{{ helper_status_ok }}'
    undercloud_conf_dns_reason: 'DNS is set up correctly in undercloud.conf'
    undercloud_conf_dns_recommendations: null
  when: undercloud_conf_dns_query|default('NXDOMAIN') != "NXDOMAIN"
  tags:
    - pre-undercloud-deploy

- name: Report DNS setup in undercloud.conf
  import_tasks: reportentry.yml
  vars:
    report_check: "DNS setup in undercloud.conf check"
    report_status: '{{ undercloud_conf_dns_status }}'
    report_host: '{{ ansible_hostname }}'
    report_reason: '{{ undercloud_conf_dns_reason }}'
    report_recommendations: '{{ undercloud_conf_dns_recommendations }}'
  tags:
    - pre-undercloud-deploy

# undercloud neutron domain check
- name: Block for neutron domain check in undercloud.conf
  when: undercloud_conf_dns_query|default('NXDOMAIN') != "NXDOMAIN"
  block:
    # NOTE(jaosorior): This returns a complete answer about the
    # query. We're just gonna get the FQDN out of this.
    - name: Get IdM/FreeIPA hostname from ip
      shell: host {{ undercloud_conf_dns_query }} | awk '{print $5}'
      register: host_from_ip_reg
      changed_when: false
      tags:
        - pre-undercloud-deploy

    - name: Get domain is set in undercloud.conf
      set_fact:
        undercloud_overcloud_domain: "{{ lookup('ini', 'overcloud_domain_name section=DEFAULT file={{ helper_undercloud_path }}/undercloud.conf') }}"
      tags:
        - pre-undercloud-deploy

    - name: Set facts undercloud.conf domain is not configured correctly
      set_fact:
        undercloud_conf_domain_status: '{{ helper_status_error }}'
        undercloud_conf_domain_reason: 'Domain is not set up correctly in undercloud.conf'
        undercloud_conf_domain_recommendations:
          - "Please set the 'overcloud_domain_name' parameter to point to the IdM/FreeIPA's domain in undercloud.conf"
      when: undercloud_overcloud_domain == "" or undercloud_overcloud_domain == [] or undercloud_overcloud_domain not in host_from_ip_reg.stdout
      tags:
        - pre-undercloud-deploy

    - name: Set facts undercloud.conf domain is configured correctly
      set_fact:
        undercloud_conf_domain_status: '{{ helper_status_ok }}'
        undercloud_conf_domain_reason: 'Domain is set up correctly in undercloud.conf'
        undercloud_conf_domain_recommendations: null
      when:
        - undercloud_overcloud_domain != ""
        - undercloud_overcloud_domain != []
        - undercloud_overcloud_domain in host_from_ip_reg.stdout
      tags:
        - pre-undercloud-deploy

    - name: Report domain setup in undercloud.conf
      import_tasks: reportentry.yml
      vars:
        report_check: "Domain setup in undercloud.conf check"
        report_status: '{{ undercloud_conf_domain_status }}'
        report_host: '{{ ansible_hostname }}'
        report_reason: '{{ undercloud_conf_domain_reason }}'
        report_recommendations: '{{ undercloud_conf_domain_recommendations }}'
      tags:
        - pre-undercloud-deploy

- name: Get enable_novajoin flag from undercloud.conf
  set_fact:
    undercloud_enable_novajoin: "{{ lookup('ini', 'enable_novajoin section=DEFAULT default=False file={{ helper_undercloud_path }}/undercloud.conf') }}"
  tags:
    - pre-undercloud-deploy

- name: Set facts undercloud.conf enable novajoin is disabled
  set_fact:
    undercloud_conf_enable_novajoin_status: '{{ helper_status_error }}'
    undercloud_conf_enable_novajoin_reason: 'enable_novajoin is not enabled undercloud.conf'
    undercloud_conf_enable_novajoin_recommendations:
      - "Please set 'enable_novajoin' to True in undercloud.conf"
  when: not undercloud_enable_novajoin|bool
  tags:
    - pre-undercloud-deploy

- name: Set facts undercloud.conf enable novajoin is enabled
  set_fact:
    undercloud_conf_enable_novajoin_status: '{{ helper_status_ok }}'
    undercloud_conf_enable_novajoin_reason: 'enable_novajoin is enabled undercloud.conf'
    undercloud_conf_enable_novajoin_recommendations: null
  when: undercloud_enable_novajoin|bool
  tags:
    - pre-undercloud-deploy

- name: Report enable novajoin setup in undercloud.conf
  import_tasks: reportentry.yml
  vars:
    report_check: "Enable novajoin setup in undercloud.conf check"
    report_status: '{{ undercloud_conf_enable_novajoin_status }}'
    report_host: '{{ ansible_hostname }}'
    report_reason: '{{ undercloud_conf_enable_novajoin_reason }}'
    report_recommendations: '{{ undercloud_conf_enable_novajoin_recommendations }}'
  tags:
    - pre-undercloud-deploy

- name: Set fact for novajoin user principal
  set_fact:
    novajoin_principal: "nova/{{ host_entry }}"
  when: ipa_conf_stat.stat.exists

- name: Set novajoin file locations if not containerized
  set_fact:
    novajoin_keytab_path: /etc/novajoin/krb5.keytab
  when:
    - not containerized_undercloud
  become: yes

- name: Set novajoin file locations if containerized
  set_fact:
    novajoin_keytab_path: /var/lib/config-data/containers/novajoin/etc/novajoin/krb5.keytab
  when:
    - containerized_undercloud

- name: verify the novajoin keytab is usable
  become: true
  tags:
    - post-undercloud-deploy
  block:
    - name: Check for novajoin kerberos host keytab
      stat:
        path: "{{ novajoin_keytab_path }}"
      register: novajoin_krb5_keytab_stat

    - name: Test if novajoin principal in novajoin keytab is usable
      command: kinit -kt "{{ novajoin_keytab_path }}" -c /tmp/my_novajoin_krb5_ccache "{{ novajoin_principal }}"
      become: true
      register: novajoin_principal_usable_result
      ignore_errors: true
      when:
        - novajoin_krb5_keytab_stat.stat.exists

    - name: Set facts for novajoin principal is usable skipped
      set_fact:
        principal_usable_status: '{{ helper_status_skipped }}'
        principal_usable_reason: "skipped checking if the novajoin principal is usable for host {{ ansible_host }} because there is no keytab file"
        principal_usable_recommendations: null
      when:
        - not novajoin_krb5_keytab_stat.stat.exists

    - name: Set facts for novajoin principal is usable success
      set_fact:
        principal_usable_status: '{{ helper_status_ok }}'
        principal_usable_reason: "The principal {{ novajoin_principal }} is able to obtain a kerberos ticket"
        principal_usable_recommendations: null
        temp_krb_caches: "{{ temp_krb_caches + [ '/tmp/my_novajoin_krb5_ccache' ] }}"
      changed_when: true
      when:
        - novajoin_krb5_keytab_stat.stat.exists
        - novajoin_principal_usable_result is succeeded
      notify:
        - clean_up_temp_krb_caches

    - name: Set facts for principal is usable failure
      set_fact:
        principal_usable_status: '{{ helper_status_error }}'
        principal_usable_reason: "Tho principal {{ novajoin_principal }} is unable to obtain a kerberos ticket"
        principal_usable_recommendations: null
      when:
        - novajoin_krb5_keytab_stat.stat.exists
        - novajoin_principal_usable_result is failed

    - name: Report principal usable status
      import_tasks: reportentry.yml
      vars:
        report_check: "Kerberos principal in novajoin keytab is usable check"
        report_status: '{{ principal_usable_status }}'
        report_host: '{{ ansible_hostname }}'
        report_reason: '{{ principal_usable_reason }}'
        report_recommendations: '{{ principal_usable_recommendations }}'
