---
- name: pre-deployment tasks
  import_tasks: pre-deploy.yml
  tags:
    - pre-undercloud-deploy

- name: post-deployment tasks
  import_tasks: post-deploy.yml
  tags:
    - post-undercloud-deploy
